<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);ASPIRECOSMOSDB001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.CosmosDB" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterviewCoach.AppHost.Core\InterviewCoach.AppHost.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterviewCoach.Agent\InterviewCoach.Agent.csproj" />
    <ProjectReference Include="..\InterviewCoach.Mcp.InterviewData\InterviewCoach.Mcp.InterviewData.csproj" />
    <ProjectReference Include="..\InterviewCoach.WebUI\InterviewCoach.WebUI.csproj" />
  </ItemGroup>

</Project>
