<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.AGUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterviewCoach.ServiceDefaults\InterviewCoach.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
